#ifndef REG_H
#define REG_H

#include"mem.h"
// flash controller的相关寄存器地址定义
#ifdef EMU
#define FCTL_BASE_ADDR 			(FCL_BASE)
#else
#define FLASH_CTL_BASE_ADDR 			0x60000000
#endif

#define FCTL_BASE_SYS_REG (FCTL_BASE_ADDR + 0x00000000)
#define FCTL_BASE_SWQ_CMD_SRAM (FCTL_BASE_ADDR + 0x00100000)
#define FCTL_BASE_SWQ_SDR_SRAM (FCTL_BASE_ADDR + 0x00200000)
#define FCTL_BASE_SWQ_DDR_SRAM (FCTL_BASE_ADDR + 0x00300000)

#define FLASH_CTL_QUEUE_SZ_PER_CH (1 * MB)
#define FLASH_CTL_REG_SZ_PER_CH (1 * MB)
#define FCTL_SZ_PER_CH (FLASH_CTL_QUEUE_SZ_PER_CH + FLASH_CTL_REG_SZ_PER_CH)
#define FCTL_CH_REG_BASE_ADDR	(FCTL_BASE_ADDR+0x00800000)
#define FCTL_CH_QUEUE_BASE_ADDR (FCTL_BASE_ADDR + 0x00900000)


#endif